---
default_set: 'ubuntu-server-12042-x64'
sets:
  'ubuntu-server-10044-x64':
    nodes:
      'main.vm':
        prefab: 'ubuntu-server-10044-x64'
  'ubuntu-server-12042-x64':
    nodes:
      'main.vm':
        prefab: 'ubuntu-server-12042-x64'
  'centos-59-x64':
    nodes:
      'main.vm':
        prefab: 'centos-59-x64'
  'debian-607-x64':
    nodes:
      'main.vm':
        prefab: 'debian-607-x64'
